"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const item_1 = require("./item");
const produto_1 = require("./produto");
let feijao;
feijao = new produto_1.Produto('Feijão preto', 5, 10);
let arroz = new produto_1.Produto('Arroz', 14.90, 25);
let it1 = new item_1.Item(feijao, feijao.valorUnit, 2);
let it2 = new item_1.Item(arroz, arroz.valorUnit, 3);
let carrinho = [it1, it2];
carrinho.push(new item_1.Item(feijao, feijao.valorUnit, 3));
console.log(carrinho);
